server:
  port: ${DISCOVERY_PORT}

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${RAILWAY_SERVICE_NAME}:${DISCOVERY_PORT}/eureka/
    instance:
      hostname: ${HOSTNAME}
      # Notes for to deploy railway Load Balancer must use Railway's private domain name instead of Local IP.
      # Set preferIpAddress as true on prod. Set preferIpAddress as false on local
      preferIpAddress: false
      non-secure-port-enabled: true
      secure-port-enabled: false
      non-secure-port: ${DISCOVERY_PORT}
      secure-port: 443
