server:
  port: ${DISCOVERY_PORT}

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  metrics:
    enable:
      processor: false
