server:
  port: ${MARKET_DATA_PORT}

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

openapi:
  service:
    title: Market Data Api doc
    version: 1.0.0
    url: http://localhost:${GATEWAY_PORT}

springdoc:
  api-docs:
    path: /market-data/v3/api-docs
  swagger-ui:
    path: /market-data/swagger-ui.html

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: health

