server:
  port: ${MARKET_DATA_PORT}

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

openapi:
  service:
    title: Market Data Api doc
    version: 1.0.0
    url: http://localhost:${GATEWAY_PORT}
    description: "*Portfolio Tracker App - This api designed for demonstration purposes only.*"
    contact:
      name: "Cem Çınar"
      email: "cmcnr82@gmail.com"
      url: "https://"

springdoc:
  api-docs:
    path: /swagger/market-data/v3/api-docs
  swagger-ui:
    path: /swagger/market-data/swagger-ui.html

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL}

management:
  metrics:
    enable:
      tomcat: false # Tomcat metrics disabled due to railway deployment server error
      jvm: false
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: "always"
  info:
    env:
      enabled: true

info:
  app:
    name: "Portfolio Tracker App - Market Data Service"
    description: "Portfolio Stocks Tracker Api. Designed for monitoring stocks and their market data. *This api designed for demonstration purposes only.*"
    developer: "Cem Çınar"