server:
  port: ${MARKET_DATA_PORT}

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

openapi:
  service:
    title: Market Data Api doc
    version: 1.0.0
    url: https://portfolio-tracker-app-dev.up.railway.app

springdoc:
  api-docs:
    path: /swagger/market-data/v3/api-docs
  swagger-ui:
    path: /swagger/market-data/swagger-ui.html

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
  instance:
    hostname: ${RAILWAY_SERVICE_NAME}
    # Notes for railway deployment
    # Load Balancer must use Railway's private domain name instead of Local IP.
    # Set preferIpAddress as true on prod. Set preferIpAddress as false on local
    preferIpAddress: false
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${MARKET_DATA_PORT}
    secure-port: 443

