server:
  port: ${PORTFOLIO_SERVICE_PORT}

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

openapi:
  service:
    title: Portfolio Service Api doc
    version: 1.0.0
    url: https://portfolio-tracker-app-dev.up.railway.app

springdoc:
  api-docs:
    path: /portfolio/v3/api-docs
  swagger-ui:
    path: /portfolio/swagger-ui.html

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
  instance:
    hostname: ${RAILWAY_SERVICE_NAME}
    # Notes for railway deployment
    # Load Balancer must use Railway's private domain name instead of Local IP.
    # Set preferIpAddress as true on prod. Set preferIpAddress as false on local
    preferIpAddress: false
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${PORTFOLIO_SERVICE_PORT}
    secure-port: 443


