server:
  port: ${WATCHLIST_SERVICE_PORT}

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

openapi:
  service:
    title: Watchlist Service Api doc
    version: 1.0.0
    url: https://portfolio-tracker-app-dev.up.railway.app
    description: "*Portfolio Tracker App - This api designed for demonstration purposes only.*"
    contact:
      name: "Cem Çınar"
      email: "cmcnr82@gmail.com"
      url: "https://"

springdoc:
  api-docs:
    path: /swagger/watchlist/v3/api-docs
  swagger-ui:
    path: /swagger/watchlist/swagger-ui.html

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
  instance:
    hostname: ${RAILWAY_SERVICE_NAME}
    # Notes for railway deployment
    # Load Balancer must use Railway's private domain name instead of Local IP.
    # Set preferIpAddress as true on prod. Set preferIpAddress as false on local
    preferIpAddress: false
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${WATCHLIST_SERVICE_PORT}
    secure-port: 443

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: "always"
  info:
    env:
      enabled: true

info:
  app:
    name: "Portfolio Tracker App - Watchlist Service"
    description: "Portfolio Stocks Tracker Api. Designed for monitoring stocks and their market data. *This api designed for demonstration purposes only.*"
    developer: "Cem Çınar"